services:
  emailmanagement.api:
    image: ${DOCKER_REGISTRY-}emailmanagementapi
    build:
      context: .
      dockerfile: EmailManagement.API/Dockerfile
  email.db: 
    image: postgres:latest
    container_name: emailm-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: emailm
    volumes:
       - ./postgres-data:/var/lib/postgresql/data 
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
volumes:
  redis_data:
  pgdata: {}